### ISSUE TITLE
Extension don't remember view states

### ISSUE THREAD

**Issue by erwannpemptroad** [NordMagnus/Trello-Folds#13]
I've tried many time on many board, by checked/unchecker the option in Trello Folds menu, but each time I come back on a board the sections I've collapsed are expanded :/
I get this pb even if I disable other extensions I use, and if I clean cache.
_(anyway it's a very good extension 👍, thank you for your job)_

**Comment by kngautham** [comment]
same Problem for me too

**Comment by NordMagnus** [comment]
Will look into it

**Comment by NordMagnus** [comment]
Works now but butt ugly solution relying on timeouts. Will try to improve later.

**Comment by ModischNeobird** [comment]
Still occurs, minimized lists are folded out on restart
