### ISSUE TITLE
Not able to use both Collapsible Sections and X to fold the list

### ISSUE THREAD

**Issue by kngautham** [NordMagnus/Trello-Folds#14]
Its a great Extension. Makes the Trello Baord easy to use. 

There is one problem though. If I use ### to turn cards into collapsible sections, The X on the list top right corner disappears for the entire board and not able to fold the lists as expected. If I remove all collapsible Sections, then X on the list top right corner comes back and becomes usable.

It looks like a bug
Thanks

**Comment by NordMagnus** [comment]
Thanks for feedback. Will look into it

**Comment by NordMagnus** [comment]
I can't reproduce this bug now. Maybe I fixed it without knowing when working  on other sections related stuff. Will close unless you can reproduce and provide more information. Sorry.
