### ISSUE TITLE
Folding of cards could evolve into having parent tasks and sub-tasks

### ISSUE THREAD

**Issue by pola3k** [NordMagnus/Trello-Folds#15]
In case of using Trello as a Scrum/Kanban board, we miss in Trello sub-tasks which can independently walk through the columns, keeping at the same time a reference to a parent tasks.
When I saw card sections in Trello Folds parent and sub-tasks came to my mind.

It would be perfect if moving a card from a section into another column would somehow keep the reference to the other cards in this section and to the section header.

It could be visualized:
- by having the section header also in a new column
- by being able to highlight all siblings of a card through all columns (or highlight somehow that not all of sub-tasks arrived to a certain column, e.g. Done)

Well. Just an idea for an improvement which would really rock.

**Comment by NordMagnus** [comment]
Thanks for suggestion.

It's a nice idea but I think it's hard to implement as a Chrome extension. It would probably require using Trello's powerup framework.

**Comment by NordMagnus** [comment]
Not possible to do in an easy way as Chrome extension. Or.....?
