### ISSUE TITLE
Combine lists

### ISSUE THREAD

**Issue by NordMagnus** [NordMagnus/Trello-Folds#16]
Combining lists with a shared WiP limit.

Any two adjacent lists named e.g.

* Super.In Progress [5]
* Super.Ready

Will be combined into a combined "parent list" named _Super_ with two "children": _In Progress_ and _Ready_

The WiP limit will be picked up from first (left) list. If one specified for right list it will be silently ignored.

(This feature should be optional so need a setting to turn it on/off)

**Comment by kngautham** [comment]
Its a great feature. Can you give us the ability to add multiple adjacent lists instead of only two?

**Comment by NordMagnus** [comment]
Will consider extending to multiple adjacent lists in future release

**Comment by kngautham** [comment]
Thanks
