### ISSUE TITLE
Use trello API

### ISSUE THREAD

**Issue by sidneydemoraes** [NordMagnus/Trello-Folds#62]
Hey Magnus. I found your work by chance and got really impressed with it. So I decided to (try to) help. I forked your code in order to send you a pull request that would allow to exclude separator cards from wip count (the ones starting with '---').

In the end I noticed that you do your magic by using jQuery to find nodes and process them. The problem is that Trello itself removes the title of separator cards nodes and adds dynamic styling for those cards, which makes impossible to filter them.

My question is: could the Trello API be used to gather data from boards? Or you really need to use DOM for that? 

You could try this:
`https://trello.com/1/lists?filter={{list_filter}}&cards={{card_filter}}&card_fields={{card_fields}}`

By replacing the mustache parts by your parameters you could gather all lists and cards from current board and work from there. 
Then you could use DOM just to add your event listeners and refresh data.

I could help you with that if you like the idea. Just let me know.

**Comment by NordMagnus** [comment]
I can have a look at it, **but** separator cards should already be excluded from WiP so sounds a bit like a bug 🤔

**Comment by NordMagnus** [comment]
Will close this as it's ooooooold. Please re-report if still relevant.
