### ISSUE TITLE
Suggestion/Request - Ability to collapse in-card Checklists?

### ISSUE THREAD

**Issue by katubug** [NordMagnus/Trello-Folds#64]
Hello! First off, thank you so much for this plugin. I am beyond stoked to try it out - it does everything I didn't realize I wanted!

I am not sure if my suggestion is within the scope of your project, or if it's even possible. So, if it's something you won't be implementing, I completely understand! However, it's how I initially found this page (googled "trello collapse checklist"), and I thought it couldn't hurt to ask.

In any case, thank you very much for your time and for the fantastic tool. I hope you have a lovely holiday season!

**Comment by NordMagnus** [comment]
I am sorry but currently I have no plans of modifying the cards themselves even it probably is possible.
