### ISSUE TITLE
Issue with Collapsing Lists

### ISSUE THREAD

**Issue by dennislin** [NordMagnus/Trello-Folds#73]
When I press X to collapse a list, the collapsed list does not move to the correct location.

![Screen Shot 2022-01-18 at 7 13 52 AM](https://user-images.githubusercontent.com/498676/149966568-78ea4fc9-7b35-432b-b16f-e19e1e83ba6f.png)
![Screen Shot 2022-01-18 at 7 14 04 AM](https://user-images.githubusercontent.com/498676/149966619-bbb6bf9d-c673-4c80-b215-90304b587ad1.png)

I see the issue in the following environments. Removing and adding back Trello Folds did not solve the issue in either case.

Google Chrome: 95.0.4638.69 (Official Build) (x86_64)
OS: macOS Version 10.13.6 (Build 17G14042)

Google Chrome: 96.0.4664.110 (Official Build) (64-bit) (cohort: Stable)
OS: Windows 10 Version 21H2 (Build 19044.1348)

**Comment by skald** [comment]
Same Issue Chrome Version 97.0.4692.99 (Official Build) (64-bit)
![1642763088911](https://user-images.githubusercontent.com/736700/150516605-bb58aaaa-ec1b-42cb-9e98-491141a5dd7c.jpg)

**Comment by NordMagnus** [comment]
Fixed. Think this was due to changes in Trellos' underlying DOM/CSS. Version 0.10.2 is about to be published with a fix for this together with some minor improvements for the board buttons (remembering collapsed state, and button hovering).
